import type { Metadata } from 'next'
import { Inter, Plus_Jakarta_Sans } from 'next/font/google'
import './globals.css'
import CustomCursor from './components/CustomCursor'
import { Footer, Navbar } from './components'

const inter = Inter({
  subsets: ['latin'],
  weight: ['400', '600', '700'],
  variable: '--font-inter',
})
const plusJakarta = Plus_Jakarta_Sans({
  subsets: ['latin'],
  weight: ['800'],
  variable: '--font-plus-jakarta'
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {


  return (
    <html lang="en">
      <head>
        {/* <link rel="icon" href="/favicon.png" type="image/png" /> */}
        {/* <script async src="https://www.googletagmanager.com/gtag/js?id=G-NC58T4ECM8"></script>
        <script
          dangerouslySetInnerHTML={{
            __html: `
              window.dataLayer = window.dataLayer || [];
              function gtag(){dataLayer.push(arguments);}
              gtag('js', new Date());
              gtag('config', 'G-NC58T4ECM8');
            `,
          }}
        /> */}
      </head>
      <body className={`${inter.variable} ${plusJakarta.variable} font-sans`}>
        <CustomCursor />
        <div className="min-h-screen flex flex-col bg-transparent">
          <Navbar />
          {children}
         
          <Footer />
        </div>
      </body>
    </html>
  )
} 